# -*- coding: utf-8 -*-
"""algerie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D4hGwPlN6jrk8RE0C9L_osZrprtdRQo3
"""

import requests
from bs4 import BeautifulSoup
import csv

# Manually define a list of song URLs (replace/add URLs as needed)
urls = [
     'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal-selma/paroles-kellem.html',
      'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-ya-ibahri.html',
      'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-des-annees.html',
      'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-y-dor.html',
      'https://paroles2chansons.lemonde.fr/paroles-kader-japonais/paroles-lwalida.html',
      'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-aicha.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-c-est-la-vie.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-didi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-abdel-kader.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-wahrane.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-delali.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-yamina.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-sbabi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-liah-liah.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-chebba.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-chebba.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-trigue-lycee.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-c-est-la-nuit.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-oran-marseille-oran-mix.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-hiya-hiya.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-bakhta.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-bakhta.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-detni-essekra.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-les-ailes.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-aalach-tloumouni.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-el-marsem.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-maghreb-gang.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-mani-hani.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-mauvais-sang.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-mektoubi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-mele-h-bibti.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-melha.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-meme-pas-fatigue.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-mirage.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-n-ssi-n-ssi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ne-m-en-voulez-pas.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ouelli-el-darek.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-raba-raba.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ragda.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-raikoum.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-sahra.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-samira.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-sbabi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-serbi-serbi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-sidi-rabi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-wahrane.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-walou-walou.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-wili-wili.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ya-aachkou.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ya-galbi.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-ya-rayah.html',
        'https://paroles2chansons.lemonde.fr/paroles-khaled/paroles-zine-a-zine.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-parisien-du-nord.html',
       'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-dellali-ha-dellali.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-nos-couleurs.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-khalouni-nebki.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-mouhal-nensa-houbi-lowel.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-meli-meli.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-bent-el-colonel.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-au-pays-des-merveilles.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-non-ce-s-ra-non.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-ouach-estalini.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-mami/paroles-viens-habibi.html',
       'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-el-aichk-el-mamnoue.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-histoire-kdima.html',
       'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-mazel-mazel.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-sma-at-biha.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-el-milieu.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-akil/paroles-jak-el-mersoul.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-hasni/paroles-el-beida-mon-amour.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-hasni/paroles-sbart-w-tal-adabi.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-hasni/paroles-ha-ma.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-hasni/paroles-choufi-omri.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-hasni/paroles-nahlef-jamais-de-la-vie.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-tellement-n-brick.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-tellement-je-t-aime.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-n-sel-fik.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-hanina.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-maina.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-eray.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-la-valse.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-mantes-la-jolie.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-omri.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-orphelin.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-baida.html',
        'https://paroles2chansons.lemonde.fr/paroles-faudel/paroles-woulli.html',
          'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-wahd-ellila-fi-paris.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sidi-rebbi-ana-rani-maghboun.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-matsalouhach.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kif-kif.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-el-babor-li-jabni.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-bki-ala-zahrek.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-bki-ala-zahrek.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-j-ai-jamais-vu-had-ezzine.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-chouf-li-kano-mouta.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-arbiya-neddiha.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-madzidiniche.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gaa-nabghou-drahem-gaa.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-di-ayza-kalam.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ntiya-omri.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-yihawas-aliya.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-zaama-twililek.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-nedik-el-paris.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ca-va-ca-va.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-abali-abala.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-jdoudna.html',
        'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-et-apres.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-farhou-gaa-elila.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-fhamha-ki-bghite.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-fini.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gaa-khfaf.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gaa-nabghou-drahem-gaa.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-galbet-el-vista.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-galbi-galbi.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ghadi-gaa-nekbahou-gaa.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ghadi-nezdem.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ghbentini-ya-denia.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ghourba-oualham.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-goul-oui.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gouli-gouli.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gouliha-hannini.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-goult-e-ndir-wahda.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gualb.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-gualou-hasni-met.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ha-hmed.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-hadi-hala.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-haja-mouhima-hadi.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-haka-ygoulou.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-harbou-lina-harbou.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-hchicha-talba-aaicha.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-hedar-heta-el-am-jay.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-henini-henini.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-hograte-nssa.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-hssabteh-rajel.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kader-rouhek.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kamlou-les-vacances.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kan-bekri.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kayen-haja.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-khouna-gaa-khfaf.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ki-deretli.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ki-ndir-m3ak-nti.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ki-rayha.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-kolchi-rah.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ksemti-belleh.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-l-an-2000.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-l-an-2000.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-la-classe.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-la-naza.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-lghorba-w-lhem.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-li-akleh-sghir.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-loukan-hessitye-bya.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-louken-ja-andi.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ma-plus-belle-histoire.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-majayache.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-mali-dayer-hak.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-maniche-nedjem.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-maniche-nedjem-nahdar.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-matsalouhach.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-men-bekri.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-milano.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-mouselsalat.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ne-me-quit-pas.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-nebki-nebki.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ness-andha-ghir-wajeh.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ok-ok.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-olla-olla.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ouili-ouili.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ouili-ouili.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-para-papiro.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-parazard.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-rak-meride-anta.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-rak-retard.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-rani-mekoui.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-roubla-son-arri.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-roubla-son-arri.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sam3ini.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sanara.html',
      "https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sid-el-hakem.html",
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sidi-sidi.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-sifini-ana-ouyek.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-souffrance.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-souhila.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-srat-li-deja.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-talaa-niveau.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-tarzan.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-thamate-aliya.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-tijara.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-wayli-wayli.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-wili-wili.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ya-layem.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-ya-salam-ala-saraha.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-yafarhouli-kisterali-haja-waara.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-yali-maalabalakch-biya.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-yeferhouli-ki-tesrali-ha-dja-ouaara.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-yeppa-mama.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-zaama-twililek.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-zazarkhatri.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bilal/paroles-zahri-darli.html',
      'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-algerie-mi-amor-lettre-d-amour-a-mon-pays.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-ssendu.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-tizi-ouzou-san-francisco.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-a-tulawin-une-algerienne-debout.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-zwit-rwit.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-isefra.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-avava-inouva.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-adrar-inu-ma-montagne.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-tagrawla.html',
      'https://paroles2chansons.lemonde.fr/paroles-idir/paroles-azger.html',
      'https://paroles2chansons.lemonde.fr/paroles-reda-taliani/paroles-merdi-l-amour.html',
      'https://paroles2chansons.lemonde.fr/paroles-reda-taliani/paroles-va-bene.html',
      'https://paroles2chansons.lemonde.fr/paroles-reda-taliani/paroles-l-etranger.html',
      'https://paroles2chansons.lemonde.fr/paroles-mohamed-lamine/paroles-retour-aux-sources.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-houssem/paroles-khatira-khatira.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheba-maria/paroles-casablanca-ft-cheba-maria.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheba-maria/paroles-gouli-je-t-aime.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheba-maria/paroles-officiel.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheba-maria/paroles-princesse-sarah.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bello/paroles-calma.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bello/paroles-frontieres.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bello/paroles-kteltini.html',
      'https://paroles2chansons.lemonde.fr/paroles-cheb-bello/paroles-toi-et-moi.html',
     'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-pas-la-peine.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-leila.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-maladie.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-milano.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-promesse.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-reste.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-rockstar.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-roloto.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-san-diego.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-sans-visa.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-santafe.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-sel3a.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-sinaloa.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-solo.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-suavemente.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-sur-pp.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-t-es-allee-ou.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-t-r-w.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-tagada.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-tata.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-te-souviens-tu.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-tichy.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-toute-ma-vie.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-unite.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-va-bene.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-vida-loca.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-vroom-vroom.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-wahda.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-wewewe.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-who-s-bad.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-woah.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-yeah.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-zabuza.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-youv.html',
   'https://paroles2chansons.lemonde.fr/paroles-soolking/paroles-zemer.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-va-bene.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-algerie-mi-amor-lettre-d-amour-a-mon-pays.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-l-autoroute-de-la-vie.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-panama.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-les-menottes.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-si-tu-savais.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-sur-la-tete-de-ma-mere.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-classi.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-y-a-des-mots-qu-on-peut-pas-dire.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-adios.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-sapapaya.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-oh-mon-papa.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-aigle-royal.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-trinite.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-andale.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-banderas.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-excuse-my-french.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-dana.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-la-vida.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-allo-maman-bobo.html',
    "https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-derapage-controle.html",
   "https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-le-chant-des-pirates.html",
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-force-et-honneur.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-gamberge.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-game-over.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-les-princes-de-la-nuit.html'
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-levez-le-voile-sur-vos-pensees.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-liberte-conditionnee.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-bonus.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-m-zia.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-m-a-r-s.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-ma-hlel.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-mal-barre.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-marchand-de-reve.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-marrakech-saint-tropez.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-mention-max.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-petit-sam.html',
   'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-quoi-de-9.html',

]

# Function to get lyrics and a specific label for a given URL
def get_song_details(url):
    soup = BeautifulSoup(requests.get(url).text, 'html.parser')

    # Get specific label (modify this part according to your needs)
    label = "2"

    # Get lyrics
    lyrics = soup.find(class_='border block-spacing-medium text-center').text.strip()

    return label, lyrics

# Main function
def main():
    # Add 100 more song URLs to the existing list
    additional_urls = [
    'https://paroles2chansons.lemonde.fr/paroles-l-algerino/paroles-quoi-de-9.html',





        # Add more URLs as needed
    ]
    urls.extend(additional_urls)

    songs_data = []

    for url in urls:
        label, lyrics = get_song_details(url)
        songs_data.append({'Label': label, 'Lyrics': lyrics})

    # Save the data to a CSV file in Colab environment
    with open('/content/song_details.csv', 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['Label', 'Lyrics']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for data in songs_data:
            writer.writerow(data)

# Execute the main function
main()

import requests
from bs4 import BeautifulSoup
import csv

# URL de la page contenant plusieurs chansons de l'artiste Khaled
url = 'https://paroles2chansons.lemonde.fr/paroles-khaled'

# Fonction pour récupérer les paroles d'une chanson à partir de son URL
def get_lyrics(song_url):
    soup = BeautifulSoup(requests.get(song_url).text, 'html.parser')
    lyrics = soup.find(class_='border block-spacing-medium text-center').text.strip()
    return lyrics

# Fonction pour récupérer les liens de chaque chanson depuis la page principale de l'artiste
def get_song_links(artist_url):
    soup = BeautifulSoup(requests.get(artist_url).text, 'html.parser')
    song_links = soup.find_all('a', class_='title')
    return [link['href'] for link in song_links]

# Fonction principale pour récupérer les paroles de toutes les chansons de l'artiste Khaled
def main():
    song_urls = get_song_links(url)
    songs_data = []

    for song_url in song_urls:
        lyrics = get_lyrics(song_url)
        songs_data.append({'Lyrics': lyrics})

    # Sauvegarder les données dans un fichier CSV
    with open('/content/khaled_songs_lyrics.csv', 'w', newline='', encoding='utf-8') as csvfile:
        fieldnames = ['Lyrics']
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)

        writer.writeheader()
        for data in songs_data:
            writer.writerow(data)

# Exécuter la fonction principale
main()